name: syvixor/skills-icons

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/syvixor-skills-icons.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash

env:
  PACKAGE_NAME: syvixor-skills-icons

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      image: ${{ steps.env-setup.outputs.docker_base_image }}
      tag: ${{ steps.env-setup.outputs.docker_tag }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout syvixor/skills-icons
        uses: actions/checkout@v4
        with:
          repository: syvixor/skills-icons
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup
        id: env-setup
        run: |
          docker_base_image="ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}"
          docker_base_image=$(echo $docker_base_image | tr '[:upper:]' '[:lower:]')
          echo "docker_base_image=$docker_base_image" >> $GITHUB_OUTPUT
          
          docker_tag="nightly"
          echo "docker_tag=$docker_tag" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.env-setup.outputs.docker_base_image }}
          tags: ${{ steps.env-setup.outputs.docker_tag }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  test:
    name: Test image
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      packages: read

    services:
      icons:
        image: "${{ needs.build.outputs.image }}@${{ needs.build.outputs.digest }}"
        ports:
          - 3000:3000
        options: >-
          --health-cmd "wget -S -T 1 -q --spider 127.0.0.1:3000"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        credentials:
          username: ${{ github.actor }}
          password: ${{ github.token }}

    steps:
      - name: Run
        run: |
          curl --verbose "127.0.0.1:3000"
          curl --verbose "127.0.0.1:3000/api/icons"
          curl --verbose "127.0.0.1:3000/api/icons?i=github"
          curl --verbose "127.0.0.1:3000/api/icons?i=github,githubactions"
  
  clean:
    name: Clean untagged
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: NorthRealm/reusable-actions/delete-untagged-ghcr-action@main
        with:
          package_name: ${{ env.PACKAGE_NAME }}
        continue-on-error: true